### ISSUE TITLE
Material in html

### ISSUE THREAD

**Issue by lgatto** [MayInstitute/MayInstitute2017#4]
@MeenaChoi - I think it would be better to use html as the output format. The new floating table of content makes navigation much easier, especially for large documents. Have a look [here](https://htmlpreview.github.io/?https://github.com/MayInstitute/MayInstitute2017/blob/master/Program3_Intro%20stat%20in%20R/01-rstats.html) for an example. What do you think?

**Comment by MeenaChoi** [comment]
No problem at all. Html is perfectly fine for me.
