### ISSUE TITLE
iPRG example data

### ISSUE THREAD

**Issue by lgatto** [MayInstitute/MayInstitute2017#7]
While working on the correlation material, I saw that 

```r
> table(iprg$Condition, iprg$BioReplicate)
            
                1    2    3    4
  Condition1 9079    0    0    0
  Condition2    0 9081    0    0
  Condition3    0    0 9081    0
  Condition4    0    0    0 9080
```

Assuming that the iPRG summary data comes from the bigger `ABRF2015_skyline_report.csv` file, I had another look at it and saw that the `Condition` and `BioReplicate` columns are all missing. When parsing the sample number and letters from the ` FileName` columns, I see that
```r
> table(let, sample)
   sample
let      1      2      3      4
  A 104811 104811 104811 104811
  B 104811 104811 104811 104811
  C 104811 104811 104811 104811
```
@MeenaChoi - should I assume that there are 3 replicates (the letters) and 4 conditions?

**Comment by lgatto** [comment]
Should I update the iPRG data?

**Comment by MeenaChoi** [comment]
Yes, there are 3 replicates/condition and 4 conditions.
ABRF2015_skyline_report.csv : the interesting variable is 'Intensity'. In this file, missing value is filled in 'Intensity' column with NA. Then it is completely balanced data (equal number of rows as we can see in table(let, sample).
iprg : this is summarized data from ABRF2015_skyline_report.csv. If there are all NAs for specific BioReplicate in 'ABRF2015_skyline_report.csv', the row for this bioreplicate in iprg can be not existed. I think that is why the first table doesn't have equal number.

**Comment by lgatto** [comment]
Sorry, I was not clear. I understand that the number of quantified features are different. My issue us that the condition and replicates (per condition) are redundant, 4 in each case (rather than 4 and 3), and completely confounded. I assume this is either a parsing error or there was an error when aggregating peptide intensities into proteins.

**Comment by lgatto** [comment]
After discussion, it turns out that there aren't any biological replicates (which doesn't really makes sense for the spike-in design at hand), but 3 technical replicates, computed below: 
```r
> iprg$TechReplicate <- factor(sub("\\.raw", "", sub(".+sample.+_", "", sub("-", "_", iprg$Run))))
> table(iprg$Condition, iprg$TechReplicate)
            
                A    B    C
  Condition1 3026 3026 3027
  Condition2 3027 3027 3027
  Condition3 3027 3027 3027
  Condition4 3027 3026 3027
```
